#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'rqt-py-console==1.0.2','console_scripts','rqt_py_console'
__requires__ = 'rqt-py-console==1.0.2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('rqt-py-console==1.0.2', 'console_scripts', 'rqt_py_console')()
    )
