#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'rqt-topic==1.2.2','console_scripts','rqt_topic'
__requires__ = 'rqt-topic==1.2.2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('rqt-topic==1.2.2', 'console_scripts', 'rqt_topic')()
    )
