#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'rqt-robot-monitor==1.0.5','console_scripts','rqt_robot_monitor'
__requires__ = 'rqt-robot-monitor==1.0.5'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('rqt-robot-monitor==1.0.5', 'console_scripts', 'rqt_robot_monitor')()
    )
