#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'rqt-reconfigure==1.0.8','console_scripts','rqt_reconfigure'
__requires__ = 'rqt-reconfigure==1.0.8'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('rqt-reconfigure==1.0.8', 'console_scripts', 'rqt_reconfigure')()
    )
